[[main]]
  name = "Home"
  pageRef = "/"
  weight = 10


[[main]]
  name = "Sobre"
  pageRef = "about"
  weight = 20

[[main]]
  name = "Blog"
  pageRef = "blog"
  weight = 30

[[main]]
  name = "Projetos"
  pageRef = "projects"
  weight = 40
  [[main]]
    name = "Exemplo de projeto"
    pageRef = "/projects/project1/"
    parent = "Projetos"
    weight = 1
  [[main]]
    name = "Outro projeto"
    pageRef = "/projects/project2/"
    parent = "Projetos"
    weight = 2
[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 50

[[social]]
  name = "LinkedIn"
  pre = "fab linkedin"
  url = "https://linkedin.com/in/ana-carolina-balbino"
  weight = 10

[[social]]
  name = "GitHub"
  pre = "fab fa-github"
  url = "https://github.com/carolbalbs"
  weight = 20

[[social]]
  name = "Discord"
  pre = "fab discord"
  url = "https://discord.gg/carolbalbs"
  weight = 30

  
  
# toml-docs-start sample-navigation
[[sample]]
name = "Blog"
pageRef = "/blog/"
weight = 10

[[sample]]
name = "Projets"
pageRef = "/projects/"
weight = 20

[[sample]]
name = "Exemple de projet"
pageRef = "/projects/project1/"
parent = "Projetos"
weight = 1

[[sample]]
name = "Autre projet"
pageRef = "/projects/project2/"
parent = "Projetos"
weight = 2
# toml-docs-end sample-navigation
