[[main]]
  name = "Home"
  pageRef = "/"
  weight = 10
[[main]]
  name = "About"
  pageRef = "about"
  weight = 20

[[main]]
  name = "Blog"
  pageRef = "blog"
  weight = 30

[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 40
  [[main]]
    name = "Sample project"
    pageRef = "/projects/project1/"
    parent = "Projects"
    weight = 1
  [[main]]
    name = "Another project"
    pageRef = "/projects/project2/"
    parent = "Projects"
    weight = 2
[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 50

[[social]]
  name = "LinkedIn"
  pre = "fab linkedin"
  url = "https://linkedin.com/in/ana-carolina-balbino"
  weight = 10

[[social]]
  name = "GitHub"
  pre = "fab fa-github"
  url = "https://github.com/carolbalbs"
  weight = 20

[[social]]
  name = "Discord"
  pre = "fab discord"
  url = "https://discord.gg/carolbalbs"
  weight = 30
  
  # toml-docs-start sample-navigation
[[sample]]
name = "Blog"
weight = 10

[[sample]]
name = "Projets"
pageRef = "/projects/"
weight = 20

[[sample]]
  name = "Sample project"
  pageRef = "/projects/project1/"
  parent = "Projects"
  weight = 1

[[sample]]
  name = "Another project"
  pageRef = "/projects/project2/"
  parent = "Projects"
  weight = 2
# toml-docs-end sample-navigation
